<?php
declare(strict_types=1);
namespace PrestaShop\Module\HB_Hscode\Entity;

use PrestaShop\Module\HB_Hscode\Repository\ProductHSCodeRepository;
use Doctrine\ORM\Mapping\ClassMetadata;
use Doctrine\ORM\Mapping\Builder\ClassMetadataBuilder;
use Doctrine\ORM\Mapping as ORM;



/**
 * @ORM\Entity()
 */
class HbProductHSCode
{
    /**
     * product ID
     * @var int
     * @ORM\Id
     * @ORM\Column(type="integer", name="id_product")
     */
    private $id_product;

    /**
     * @var ?string
     * @ORM\Column(type="string", nullable=true, name="hs_code")
     */
    private $hs_code;

    /**
     * @var bool forces the id to be set before saving object (because we don't need autogenerated id for this model)
     */
    public $force_id = true;

    public function getIdProduct(): int
    {
        return $this->id_product;
    }

    public function setIdProduct(int $id_product): self
    {
        $this->id_product = $id_product;
        return $this;
    }

    public function getHsCode(): ?string
    {
        return $this->hs_code;
    }

    public function setHsCode(?string $hs_code): self
    {
        $this->hs_code = $hs_code;
        return $this;
    }
}
